### ISSUE TITLE
Create a great README.md file in pt-br / en-en

### ISSUE THREAD

**Issue by anasilveira9787** [anasilveira9787/playing-with-Javascript#2]

**Comment by ARH-MNAJS** [comment]
Hey, @anasilveira9787 I can write an excellent README.md file for your project in English as well as in Portuguese. Can u assign this to me?

**Comment by anasilveira9787** [comment]
@ARH-MNAJS  Thank you for your help! As this is an hacktoberfest repo and you're already assigned to another issue, I will let other users  to do this task, so more people can enjoy the party, ok?

**Comment by ARH-MNAJS** [comment]
works🤟

**Comment by bpires** [comment]
Hey @anasilveira9787, can you assign me this task? I'd love to work on this!
